language: java
before_script: "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./make_credentials.py"
script: mvn clean test

# If building master, Publish to Sonatype
after_success: "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && mvn deploy"

#sudo: false

# Cache settings
#cache:
#  directories:
#    - $HOME/.m2/repository

# whitelist
branches:
  only:
    - master
